In [13]:
import numpy as np

class Matrices:
    def __init__(self, matrix):
        self.matrix = np.array(matrix)

    def determinante(self):
        return np.linalg.det(self.matrix)

    def inversa(self):
        return np.linalg.inv(self.matrix)

    def transpuesta(self):
        return np.transpose(self.matrix)

class MatricesOperaciones(Matrices):
    def __init__(self, matrix):
        super().__init__(matrix)

    def rotacion(self, angle_degrees):
        angle_radians = np.radians(angle_degrees)
        rotation_matrix = np.array([[np.cos(angle_radians), -np.sin(angle_radians)],
                                   [np.sin(angle_radians), np.cos(angle_radians)]])
        return np.dot(rotation_matrix, self.matrix)

# Ejemplo práctico de las definiciones anteriores
matrix_data = [[7, 9], [5, 4]]
matrices_obj = Matrices(matrix_data)

print("Matriz Original:")
print(matrices_obj.matrix)

print("\nDeterminante de la Matriz:")
print(matrices_obj.determinante())

print("\nInversa (f'-1):")
print(matrices_obj.inversa())

print("\nTranspuesta:")
print(matrices_obj.transpuesta())

# Operación rotación usando la clase heredada
matrices_op_obj = MatricesOperaciones(matrix_data)

angle_to_rotate = 65
rotated_matrix = matrices_op_obj.rotacion(angle_to_rotate)

print(f"\nRotación de {angle_to_rotate} grados:")
print(rotated_matrix)






Matriz Original:
[[7 9]
 [5 4]]

Determinante de la Matriz:
-16.999999999999993

Inversa (f'-1):
[[-0.23529412  0.52941176]
 [ 0.29411765 -0.41176471]]

Transpuesta:
[[7 5]
 [9 4]]

Rotación de 65 grados:
[[-1.5732111   0.17833321]
 [ 8.45724582  9.84724313]]
